fedup - the Fedora Upgrader
===========================
Will Woods <wwoods@redhat.com>
:fedup_dracut: https://github.com/wgwoods/fedup-dracut/

This is 'fedup', the Fedora Upgrade tool. This repo/package has the following
contents:

Frontend / pre-upgrade::
    This is the GUI/CLI frontend. It's responsible for setting up the system
    to be upgraded: downloading packages, modifying the bootloader, etc.
    * Files: `fedup/`, `fedup-cli`, `fedup-gtk` (and `ui/`)

Upgrade services::
    Part of a distro-neutral framework for performing major system upgrades
    using 'systemd' and 'dracut', with a 'plymouth' progress screen.
    This part lets your system switch back to the upgrade initramfs after
    setting up your disks.
    * Files: `systemd/`

The actual upgrade is handled inside the initramfs by 'fedup-dracut', which
can be found here: {fedup_dracut}

How to test
-----------

You'll need two build environments - one for the _new_ system and one for the
_old_ system.

New System::
    Install 'fedup-dracut' and build upgrade initramfs (`upgrade.img`).
    See {fedup_dracut}[the fedup-dracut README] for details.

Old System::
    . Install build requirements
        * 'python-devel'
    . Install frontend(s) and systemd support files
        * `make install`
    . Run fedup to prepare system
        * This will take a while. _Be patient._
        * If you have a test repo with `.treeinfo`, kernel, and initrd:
            ** `fedup-cli --network 18 --repo my-tree=http://... --instrepo my-tree`
        * Otherwise:
            ** `fedup-cli --network 18 --skipkernel`
            ** `mkdir /boot/upgrade`
            ** Copy kernel from _new_ system to `/boot/upgrade/vmlinuz`
            ** Copy `upgrade.img` to `/boot/upgrade/upgrade.img`
    . Reboot into *System Upgrade* boot menu item
        * *NOTE:* this has to be chosen manually right now
    . Wait 60-90 minutes for the upgrade to complete


// vim: syntax=asciidoc tw=78:
