#!/bin/sh

target=/usr/lib/systemd/system/system-upgrade.target

if [ -f /run/initramfs/start-system-upgrade -a \
     -d /system-upgrade -a -L /system-upgrade -a -f "$target" ]; then
    ln -sf "$target" "${2:-$1}/default.target"
fi
